In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
import statsmodels.api as sm
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn import preprocessing
from scipy import stats
from scipy.special import boxcox1p
from mpl_toolkits.mplot3d import Axes3D

In [7]:
Pest = pd.read_excel('PESTEXCEL.xlsx')
Pest

,AIAccess,RAAccess,PsRsChoose,ESAfford,FVTBenefit,GMCBenefit,AOConvinient,CSExcellent
0,5,5,5,5,5,5,5,5
1,4,4,4,4,4,4,4,4
2,4,4,2,1,5,5,2,4
3,3,3,2,2,4,3,4,3
4,4,5,4,5,5,5,4,4
...,...,...,...,...,...,...,...,...
123,4,4,4,4,4,4,4,4
124,3,3,2,3,3,4,4,4
125,3,3,4,4,4,4,4,2
126,2,2,2,2,4,4,4,4
127,4,3,2,3,4,4,4,4

In [11]:
#MEAN
Pest.mean()
#Pest['AIAccess'].mean(), to calculate the mean of a single column.

AIAccess        3.609375
RAAccess        3.453125
PsRsChoose      3.398438
ESAfford        3.625000
FVTBenefit      3.937500
GMCBenefit      3.789062
AOConvinient    3.898438
CSExcellent     3.453125
dtype: float64

In [13]:
#MEDIAN
Pest.median()

AIAccess        4.0
RAAccess        4.0
PsRsChoose      3.5
ESAfford        4.0
FVTBenefit      4.0
GMCBenefit      4.0
AOConvinient    4.0
CSExcellent     4.0
dtype: float64

In [15]:
#MODE
Pest.mode()

,AIAccess,RAAccess,PsRsChoose,ESAfford,FVTBenefit,GMCBenefit,AOConvinient,CSExcellent
0,4,4,4,4,4,4,4,4

In [35]:
#Lower Quartile
Pest.quantile([0.25])

,AIAccess,RAAccess,PsRsChoose,ESAfford,FVTBenefit,GMCBenefit,AOConvinient,CSExcellent
0.25,3.0,3.0,3.0,3.0,4.0,3.0,4.0,3.0

In [37]:
#Upper Quartile
Pest.quantile([0.75])

,AIAccess,RAAccess,PsRsChoose,ESAfford,FVTBenefit,GMCBenefit,AOConvinient,CSExcellent
0.75,4.0,4.0,4.0,4.0,4.0,4.0,5.0,4.0

In [39]:
#CALCULATING DISPERSION BELOW

In [47]:
#STANDARD DEVIATION
Pest.std()

AIAccess        0.805829
RAAccess        0.868154
PsRsChoose      0.958508
ESAfford        0.947437
FVTBenefit      0.830046
GMCBenefit      0.961072
AOConvinient    0.962607
CSExcellent     1.018408
dtype: float64

In [45]:
#COEFF OF SKEWNESS
Pest.skew()

AIAccess       -1.004742
RAAccess       -0.880516
PsRsChoose     -0.386635
ESAfford       -0.818282
FVTBenefit     -1.476518
GMCBenefit     -0.861143
AOConvinient   -1.085205
CSExcellent    -0.370805
dtype: float64